services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: almaweb_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rootroot
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: >
      sh -c "./wait-for-it.sh db:5432 --
      && python manage.py migrate
      && python manage.py createsuperuser --noinput || true
      && python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    depends_on:
      - db

volumes:
  postgres_data:
