services:
  web:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      DJANGO_SUPERUSER_USERNAME: ${DJANGO_SUPERUSER_USERNAME}
      DJANGO_SUPERUSER_EMAIL: ${DJANGO_SUPERUSER_EMAIL}
      DJANGO_SUPERUSER_PASSWORD: ${DJANGO_SUPERUSER_PASSWORD}
    volumes:
      - /srv/charity/media:/app/media
      - ./staticfiles:/app/staticfiles
    command: >
      sh -lc "
        python manage.py collectstatic --noinput &&
        python manage.py migrate --noinput &&
        python manage.py shell -c 'from django.contrib.auth import get_user_model; import os; U=get_user_model(); u=os.environ.get(\"DJANGO_SUPERUSER_USERNAME\"); e=os.environ.get(\"DJANGO_SUPERUSER_EMAIL\"); p=os.environ.get(\"DJANGO_SUPERUSER_PASSWORD\"); 
      if u and p and not U.objects.filter(username=u).exists(): U.objects.create_superuser(u,e,p)' &&
      gunicorn CharityAlmaWeb.wsgi:application -b 0.0.0.0:8000 --workers 3
      "
    ports:
      - "8004:8000"
