# Generated by Django 5.1.3 on 2025-06-30 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_product_category_product_main_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('available', 'Доступно'), ('requested', 'Запрошено'), ('exchanged', 'Обмен запрошен'), ('taken', 'Забрано')], default='available', max_length=20, verbose_name='Статус'),
        ),
    ]
