# Generated by Django 5.1.3 on 2025-07-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_product_status_traderequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Одобрено модератором'),
        ),
    ]
