# Generated by Django 5.1.3 on 2025-11-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_category_id_alter_product_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('free', 'Отдаю даром'), ('exchange', 'Обмен'), ('rental', 'Аренда')], max_length=10),
        ),
    ]
