# Generated by Django 5.2.8 on 2026-03-02 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_productimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='action',
            field=models.CharField(choices=[('take', 'Забрать'), ('rent', 'Аренда'), ('exchange', 'Обмен')], max_length=10, verbose_name='Действие'),
        ),
    ]
