# Generated by Django 5.2.8 on 2026-04-28 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_traderequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='desired_categories',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='traderequest',
            name='offered_item',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
