# Generated by Django 5.1.3 on 2025-11-07 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('core', '0007_alter_product_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chats', to='core.product', verbose_name='Товар'),
        ),
    ]
