# Generated by Django 5.2.8 on 2025-11-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_image_alter_message_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('sent', 'Отправлено'), ('read', 'Прочитано')], default='sent', max_length=10),
        ),
    ]
