# Generated by Django 5.2.8 on 2026-03-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_pushsubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pushsubscription',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
